---
title: "QTM 151: Introduction to Statistical Computing II"
---

Welcome to [QTM151 - Introduction to Statistical Computing
II!](https://github.com/danilofreire/qtm151) This repository contains all the
materials for the course, including lectures, assignments, quizzes, and
tutorials.

## Course Overview

This course is designed to introduce students to statistical computing
techniques using Python and SQL. It builds upon the foundational knowledge from
QTM150 and focuses on practical applications of data analysis, reproducible
research, and database management.

## Repository Structure

The [course's GitHub repository](https://github.com/danilofreire/qtm151) is organised as follows:

- [`assignments/`](https://github.com/danilofreire/qtm151/tree/main/assigments): Contains all course assignments
- [`lectures/`](https://github.com/danilofreire/qtm151/tree/main/lectures): Includes lecture materials and code
- [`quizzes/`](https://github.com/danilofreire/qtm151/tree/main/quizzes): Quiz materials
- [`tutorials/`](https://github.com/danilofreire/qtm151/tree/main/tutorials): Step-by-step guides for the tools used in the course
- [`README.md`](https://github.com/danilofreire/qtm151/blob/main/README.md): This file, providing an overview of the course and repository
- [`syllabus.pdf`](https://github.com/danilofreire/qtm151/blob/main/syllabus.pdf): Course syllabus in PDF format

**Note**: The links will take you to the respective folders or files in the
repository, not to this website. You can find links for the rendered content in
the navigation bar above.

## Course Content

### Lectures

The course covers the following main topics, with corresponding lecture
materials available in the [lectures
folder](https://github.com/danilofreire/qtm151/tree/main/lectures):

## Lectures

1. Lecture 01: [Welcome to QTM 151 - Introduction](https://danilofreire.github.io/qtm151/lectures/lecture-01/01-introduction.html)
2. Lecture 02: [GitHub Review](https://danilofreire.github.io/qtm151/lectures/lecture-02/02-github-review.html) and [Introduction to Jupyter Notebooks](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-02/02-jupyter.ipynb)
3. Lecture 03: [Variables and Lists](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-03/03-variables-lists.ipynb)
4. Lecture 04: [Mathematical Operations, Arrays, and Random Numbers](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-04/04-maths-arrays-random.ipynb)
5. Lecture 05: [Boolean Variables and If/Else Statements](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-05/05-boolean-if-else.ipynb)
6. Lecture 06: [While Loops and For Loops](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-06/06-while-for.ipynb)
7. Lecture 07: [Applications 1: Simulation Studies](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-07/07-applications-simulation.ipynb)
8. Lecture 08: [Functions and Arguments](https://danilofreire.github.io/qtm151/lectures/lecture-08/08-functions-arguments.ipynb)
9. Lecture 09: [Global and Local Variables](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-09/09-global-local.ipynb)
10. Lecture 10: [**Quiz 01: Application 02 - Operations over Multiple Datasets (6%)**](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-10/10-operations-multiple-datasets.ipynb)
11. Lecture 11: [Subsetting Data](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-11/11-subsetting-data.ipynb)
12. Lecture 12: [Application 03: Linear Models](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-12/12-linear-models.ipynb)
13. Lecture 13: [Creating and Replacing Variables](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-13/13-creating-replacing-variables.ipynb)
14. Lecture 14: [**Quiz 2: Application 4: Random Assignment (6%)**](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-14/14-random-assignment.ipynb)
15. Lecture 15: [Aggregating Data](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-15/15-aggregating-data.ipynb)
16. Lecture 16: [Merging Data](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-16/16-merging-data.ipynb)
17. Lecture 17: [Introduction to SQL](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-17/17-introduction-sql.ipynb)
18. Lecture 18: [**Quiz 3: Application 5: Practicing Chaining (6%)**](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-18/18-chaining.ipynb)
19. Lecture 19: [Import SQL Data into Python](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-19/19-sql-python.ipynb)
20. Lecture 20: [Merging Tables in SQL](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-20/20-sql-merging.ipynb)
21. Lecture 21: [Time Series Analysis](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-21/21-time-series.ipynb)
22. Lecture 22: [**Quiz 4: Application 6: Practice SQL Queries (6%)**](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-22/22-sql-queries.ipynb)
23. Lecture 23: [Pivot Tables](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-23/23-pivot-tables.ipynb)
24. Lecture 24: [**Quiz 5: Application 8: Time Data, Panel Data, and Plots (6%)**](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-24/24-time-panel-plots.ipynb)
25. Lecture 25: [Manipulating Text Data](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-25/25-text-data.ipynb)
26. Lecture 26: [Advanced Plots](https://github.com/danilofreire/qtm151/blob/main/lectures/lecture-26/26-advanced-plots.ipynb)

Each lecture folder contains a Jupyter notebook (.ipynb) with code examples and
explanations, along with any additional resources or datasets used in the
lecture.

## Assignments and Quizzes

Throughout the course, students will complete various assignments and quizzes
to reinforce their learning. These will be posted in the respective
[`assignments/`](https://github.com/danilofreire/qtm151/tree/main/assigments)
and [`quizzes/`](https://github.com/danilofreire/qtm151/tree/main/quizzes)
folders as the course progresses. We will also announce these in class and on
Canvas. Please refer to the syllabus for due dates and submission guidelines.

### Tutorials

The [`tutorials/`](https://github.com/danilofreire/qtm151/tree/main/tutorials)
folder contains step-by-step guides for various tools and techniques used in
the course. These include:

- [VSCode and Anaconda Tutorial](https://github.com/danilofreire/qtm151/blob/main/tutorials/01-vscode-anaconda-tutorial.pdf)
- [Jupyter Notebook and Markdown Tutorial](https://github.com/danilofreire/qtm151/blob/main/tutorials/02-jupyter-markdown-tutorial.pdf)
- [GitHub Tutorial](https://github.com/danilofreire/qtm151/blob/main/tutorials/03-github-tutorial.pdf)
- [PostgreSQL Tutorial](https://github.com/danilofreire/qtm151/blob/main/tutorials/04-postgresql-tutorial.pdf)

## Course Requirements

- Prerequisites: None, only willingness to learn and explore new tools :smiley:
- Software: [Anaconda distribution of Python 3.x](https://www.anaconda.com/), [VS Code](https://code.visualstudio.com/), [PostgreSQL](https://www.postgresql.org/), [GitHub Desktop](https://github.com/apps/desktop)

## Grading

- Assignments: 50%
- Class Quizzes: 30%
- Final Project: 20%
- Mid-semester and end-of-semester evaluations: 0.5% each, bonus

## Course Policies and Expectations

For detailed information on course policies, grading criteria, attendance
requirements, and academic integrity guidelines, please refer to the
[`syllabus.pdf`](https://github.com/danilofreire/qtm151/blob/main/syllabus.pdf)
file in the repository root.

## Suggested Resources

To supplement your learning, you may find the following resources helpful:

### Books

- [Python for Data Analysis](https://wesmckinney.com/book/) by Wes McKinney
- [Elements of Data Science](https://allendowney.github.io/ElementsOfDataScience/README.html) by Allen Downey
- [Automate the Boring Stuff with Python](https://automatetheboringstuff.com) by Al Sweigart
- [Python for Everybody](https://www.py4e.com/book.php) by Charles Severance
- [SQL for Data Scientists](https://sqlfordatascientists.com/) by Renee M. P. Teate

### Online Courses

- [Coursera: Python for Everybody Specialisation](https://www.coursera.org/specializations/python)
- [edX: Python Basics for Data Science](https://www.edx.org/learn/python/ibm-python-basics-for-data-science)
- [Codecademy: Learn Python](https://www.codecademy.com/learn/learn-python-3)
- [DataCamp: Introduction to SQL](https://www.datacamp.com/courses/intro-to-sql-for-data-science)
- [Coursera: SQL for Data Science](https://www.coursera.org/learn/sql-for-data-science)

### Documentation

- [Official Python Documentation](https://docs.python.org/3/)
- [NumPy Documentation](https://numpy.org/doc/)
- [Pandas Documentation](https://pandas.pydata.org/docs/)
- [Matplotlib Documentation](https://matplotlib.org/stable/contents.html)
- [PostgreSQL Documentation](https://www.postgresql.org/docs/)

The syllabus also includes a list of additional readings and resources for each week.

## Contact Information

- Instructor: Danilo Freire
- Email: danilo.freire@emory.edu
- Office Hours: At your convenience, please schedule an appointment via email.

## Academic Integrity

Students are expected to adhere to the [Emory University Honour
Code](https://catalog.college.emory.edu/policies/honor-code.html). Any
suspected violations will be reported to the Honour Council.

## Accessibility

If you require any accommodations for this course, please contact the
[Department of Accessibility Services](https://accessibility.emory.edu/) and
the instructor as soon as possible.

## Getting Help

If you encounter any issues with the course materials or have questions about the content, please:

1. Check the [course syllabus](https://github.com/danilofreire/qtm151/blob/main/syllabus.pdf) and this README for relevant information
2. Review the [lecture materials](https://github.com/danilofreire/qtm151/tree/main/lectures) and [tutorials](https://github.com/danilofreire/qtm151/tree/main/tutorials) in the repository
3. Consult with your classmates or post in the [course discussion forum](https://github.com/danilofreire/qtm151/discussions)
4. Attend office hours or schedule an appointment with the instructor

## Contributing to the Repository

While this repository is primarily maintained by the course instructor,
everyone is welcome to contribute. Please feel free to suggest improvements or
report issues by [opening a GitHub
issue](https://github.com/danilofreire/qtm151/issues), [submitting a pull
request](https://github.com/danilofreire/qtm151/pulls), [creating a discussion
post](https://github.com/danilofreire/qtm151/discussions), or [contacting the
instructor directly](mailto:danilo.freire@emory.edu).

## Acknowledgements

This course and its materials have been developed with inspiration from
previous version of this course, as well as various open-source communities and
educational resources. I am particularly grateful to [Alejandro Sánchez
Becerra](https://sites.google.com/site/sanchezbecerraalejandro/teaching_1) for
his teaching materials and guidance. I am also thankful for the contributions
of the Python, SQL, and data science communities that make courses like this
possible.

## License

This repository is licensed under the [MIT License](LICENSE.qmd). You are
free to use, modify, and distribute the materials as needed, with appropriate
attribution to the original source.

-----

We look forward to an engaging and productive semester! Good luck, and happy coding! :smiley:
